version: "3.9"

services:
  web:
    build: .
    container_name: product_catalog
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    networks:
      - catalog-network

  db:
    image: "mongo:8.0.14-noble"
    container_name: mongo_catalog
    restart: always
    env_file:
      - .env
    ports:
      - "27018:27017"
    volumes:
      - my_db:/data/db
    networks:
      - catalog-network

volumes:
  my_db:

networks:
  catalog-network:
    driver: bridge